application: flowdle
version: 2
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /javascripts
  static_dir: javascripts

- url: /errors
  static_dir: errors
  
- url: /
  script: index.py

- url: /index.html
  script: index.py

- url: /app(.*)
  script: app.py
  login: required

- url: /rpc(.*)
  script: rpc.py
  login: required

- url: /nudger/send
  script: nudger.py
  
 
