application: flowdle
version: 2
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

- url: /errors
  static_dir: errors
  
- url: /
  script: index.py

- url: /index.html
  script: index.py

- url: /app(.*)
  script: app.py
  login: required

- url: /edit/(.*)
  script: app.py
  login: required
