application: flowdle
version: 3
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /javascripts
  static_dir: javascripts

- url: /errors
  static_dir: errors
  
- url: /
  script: python/main.py

- url: /logout
  script: python/logout.py

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /index.html
  script: python/main.py

- url: /closed(.*)
  script: python/main.py

- url: /settings
  script: python/settings.py
  login: required
  
- url: /feedback
  script: python/feedback.py
  login: required

- url: /app(.*)
  script: python/app.py
  login: required

- url: /rpc(.*)
  script: python/rpc.py
  login: required

- url: /nudger(.*)
  script: python/nudger.py

  
 
